{{- if and .Values.externalSecrets.enabled .Values.pagerDuty.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-squad-paging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.pagerDuty.secretName }}
  data:
    - secretKey: {{ .Values.pagerDuty.routingKeySecretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.secretPath }}
        property: {{ .Values.pagerDuty.vaultProperty }}
{{- end }}
