apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Supply Chain
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      The :latest tag must not be used for container images.
      All images must reference a specific version or digest.
spec:
  validationFailureAction: {{ .Values.admission.noLatest.enforce | default "Audit" }}
  background: false
  rules:
    - name: validate-no-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Image must not use the :latest tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
            =(initContainers):
              - image: "!*:latest"
